### PR TITLE
Split parser and datastore

### PR DESCRIPTION
**Pull request by yodalee**
A PR that split parser and datastore.
Each commit split one parser for easy to review the change, and they can be squashed before merge.
The datastore should move to upper layer, but this will cause error by cross reference.

### CODE REVIEW

**Comment by aitjcize** [comment]
You should move the 'datastore' classes to the parser directory, since it should be independent of parser. Also move files under record/* to parser/* (promote the files under record and just put them in the parser directory), each sub-directory in the parser directory contains the code for one parser.

**Comment by aitjcize** [comment]
Oh I saw your PR comment, what do you mean by cross reference error?

**Comment by yodalee** [comment]
Updated, now datastore is at upper layer.

**Comment by aitjcize** [comment]
LGTM

**Comment by aitjcize** [comment]
[LGTM](http://lgtm.in/i/GR89xEKdq)

[:+1:](http://lgtm.in/u/GR89xEKdq)
送妳妹子以資鼓勵XD

**Comment by yodalee** [comment]
[LGTM](http://lgtm.in/i/KVlZQuOhq)

**Pull request merged**
